# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flamework_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('engineer', 'エンジニア'), ('designer', 'デザイナー')], default='engineer', max_length=16),
        ),
    ]
